# Exercise: Analysing stock data using NumPy

### Stage 3: Reshape Stock Prices and Calculate Moving Averages
Objective: Use NumPy’s reshape() to change the shape of a stock price matrix. After reshaping the data, calculate a 3-day moving average for each stock and display the results.

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import datetime

print(f"NumPy version: {np.__version__}")
print(f"Matplotlib version: {plt.matplotlib.__version__}")
print(f"Date: {datetime.datetime.now()}")

NumPy version: 1.26.4
Matplotlib version: 3.9.0
Date: 2024-10-14 23:04:10.315827


In [9]:
# Load Data from CSV, prices should be a 1D array
dates = np.genfromtxt("../data/numpy1.csv", delimiter=",", dtype="str", skip_header=1, usecols=0)
prices = np.genfromtxt("../data/numpy1.csv", delimiter=",", dtype="float", skip_header=1, usecols=(1, 2, 3)).flatten()

dates = [datetime.datetime.strptime(date, "%Y-%m-%d") for date in dates]

print(prices)

[102.01 151.2  197.96 100.58 149.79 204.93 102.3  152.01 202.05 105.51
 151.71 197.67 105.34 147.19 199.08 107.   148.   200.1  106.5  149.5
 202.4  108.1  150.   201.7  109.5  148.9  203.   110.   150.2  202.8 ]


In [10]:
# Reshape prices to a 2D array
prices = prices.reshape(-1, 3)
print(prices)

[[102.01 151.2  197.96]
 [100.58 149.79 204.93]
 [102.3  152.01 202.05]
 [105.51 151.71 197.67]
 [105.34 147.19 199.08]
 [107.   148.   200.1 ]
 [106.5  149.5  202.4 ]
 [108.1  150.   201.7 ]
 [109.5  148.9  203.  ]
 [110.   150.2  202.8 ]]


In [14]:
# Define a Moving Average Function
def moving_average(data, window_size):
    weights = np.ones(window_size) / window_size
    return np.convolve(data, weights, mode="valid")

# Apply the moving average function to the prices
stock_names = ["Stock 1", "Stock 2", "Stock 3"]
window_size = 3
ma_prices = [moving_average(prices[:, i], window_size) for i in range(3)]

# Skip the first window_size - 1 dates, which have no moving average
ma_dates = dates[window_size - 1:]

print("Reshaped Prices:")
print(prices)

print("\nMoving Average Prices:")
for stock_name in stock_names:
    print(f"\n{stock_name} Moving Averages:")
    for date, ma_value in zip(ma_dates, ma_prices[stock_names.index(stock_name)]):
        print(f"{date}: {ma_value:.2f}")


Reshaped Prices:
[[102.01 151.2  197.96]
 [100.58 149.79 204.93]
 [102.3  152.01 202.05]
 [105.51 151.71 197.67]
 [105.34 147.19 199.08]
 [107.   148.   200.1 ]
 [106.5  149.5  202.4 ]
 [108.1  150.   201.7 ]
 [109.5  148.9  203.  ]
 [110.   150.2  202.8 ]]

Moving Average Prices:

Stock 1 Moving Averages:
2024-01-03 00:00:00: 101.63
2024-01-04 00:00:00: 102.80
2024-01-05 00:00:00: 104.38
2024-01-06 00:00:00: 105.95
2024-01-07 00:00:00: 106.28
2024-01-08 00:00:00: 107.20
2024-01-09 00:00:00: 108.03
2024-01-10 00:00:00: 109.20

Stock 2 Moving Averages:
2024-01-03 00:00:00: 151.00
2024-01-04 00:00:00: 151.17
2024-01-05 00:00:00: 150.30
2024-01-06 00:00:00: 148.97
2024-01-07 00:00:00: 148.23
2024-01-08 00:00:00: 149.17
2024-01-09 00:00:00: 149.47
2024-01-10 00:00:00: 149.70

Stock 3 Moving Averages:
2024-01-03 00:00:00: 201.65
2024-01-04 00:00:00: 201.55
2024-01-05 00:00:00: 199.60
2024-01-06 00:00:00: 198.95
2024-01-07 00:00:00: 200.53
2024-01-08 00:00:00: 201.40
2024-01-09 00:00:00: 202